name: GitHub Snake Game

on:
  # Executa diariamente à meia-noite UTC
  schedule:
    - cron: "0 0 * * *"
  # Permite execução manual
  workflow_dispatch:
  # Executa quando houver push na branch main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout o repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2.1: Gera SVG padrão
      - name: Generate Snake SVG (light)
        uses: Platane/snk@v3
        with:
          github_user_name: ArthurMoraeszx
          output_path: dist/github-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 2.2: Gera SVG com tema dark
      - name: Generate Snake SVG (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: ArthurMoraeszx
          output_path: dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 2.3: Gera GIF customizado
      - name: Generate Snake GIF (custom colors)
        uses: Platane/snk@v3
        with:
          github_user_name: ArthurMoraeszx
          output_path: dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Publica na branch output
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
